default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: db

development:
  <<: *default
  host: <%= Rails.application.credentials.rds[:host] %>
  database: <%= Rails.application.credentials.rds[:database] %>
  username: <%= Rails.application.credentials.rds[:username] %>
  password: <%= Rails.application.credentials.rds[:password] %>
  port: <%= Rails.application.credentials.rds[:port] %>

test:
  <<: *default
  host: <%= Rails.application.credentials.rds[:host] %>
  database: <%= Rails.application.credentials.rds[:database] %>
  username: <%= Rails.application.credentials.rds[:username] %>
  password: <%= Rails.application.credentials.rds[:password] %>
  port: <%= Rails.application.credentials.rds[:port] %>

  production:
    <<: *default
    host: <%= Rails.application.credentials.rds[:host] %>
    database: <%= Rails.application.credentials.rds[:database] %>
    username: <%= Rails.application.credentials.rds[:username] %>
    password: <%= Rails.application.credentials.rds[:password] %>
    port: <%= Rails.application.credentials.rds[:port] %>